obj-$(CONFIG_MACH_MSM8930_LGPS9) += board-lgps9.o \
	board-lgps9-camera.o \
	board-lgps9-display.o \
	board-lgps9-gpiomux.o \
	board-lgps9-gpu.o \
	board-lgps9-pmic.o \
	board-lgps9-regulator.o \
	board-lgps9-rfkill.o \
	board-lgps9-storage.o \
	board-lgps9-usb.o \
	board-lgps9-input.o \
	board-lgps9-sensor.o \
	board-lgps9-sound.o
