ifdef CONFIG_MACH_LGE_FX3_VZW
obj-y += board-fx3.o \
	board-fx3-camera.o \
	board-fx3-display.o \
	board-fx3-gpiomux.o \
	board-fx3-gpu.o \
	board-fx3-pmic.o \
	board-fx3-regulator.o \
	board-fx3-rfkill.o \
	board-fx3-storage.o \
	board-fx3-usb.o \
	board-fx3-input-vzw.o \
	board-fx3-sensor-vzw.o \
	board-fx3-sound.o \
	board-fx3-misc.o \
	board-fx3-nfc.o

else
ifdef CONFIG_MACH_LGE_FX3Q_TMUS
obj-y += board-fx3.o \
	board-fx3-camera.o \
	board-fx3-display.o \
	board-fx3-gpiomux.o \
	board-fx3-gpu.o \
	board-fx3-pmic.o \
	board-fx3-regulator.o \
	board-fx3-rfkill.o \
	board-fx3-storage.o \
	board-fx3-usb.o \
	board-fx3-input-vzw.o \
	board-fx3-sensor-vzw.o \
	board-fx3-sound.o \
	board-fx3-nfc.o\
	board-fx3-misc.o
else
ifdef CONFIG_TOUCHSCREEN_MELFAS_MMS134
	obj-y += board-fx3.o \
	board-fx3-camera.o \
	board-fx3-display.o \
	board-fx3-gpiomux.o \
	board-fx3-gpu.o \
	board-fx3-pmic.o \
	board-fx3-regulator.o \
	board-fx3-storage.o \
	board-fx3-usb.o \
	board-f6-input.o \
	board-fx3-sensor.o \
	board-fx3-sound.o \
	board-fx3-nfc.o \
	board-f6-misc.o \
	board-fx3-rfkill.o 
else
ifdef CONFIG_MACH_LGE_L9II_COMMON
ifdef CONFIG_NFC_BCM43341
	obj-y += board-fx3.o \
	board-fx3-camera.o \
	board-fx3-display.o \
	board-fx3-gpiomux.o \
	board-fx3-gpu.o \
	board-fx3-pmic.o \
	board-fx3-regulator.o \
	board-fx3-rfkill.o \
	board-fx3-storage.o \
	board-fx3-usb.o \
	board-fx3-input-l9ii.o \
	board-fx3-sensor.o \
	board-fx3-sound.o \
	board-fx3-nfc.o \
	board-l9ii-misc.o
else
	obj-y += board-fx3.o \
	board-fx3-camera.o \
	board-fx3-display.o \
	board-fx3-gpiomux.o \
	board-fx3-gpu.o \
	board-fx3-pmic.o \
	board-fx3-regulator.o \
	board-fx3-rfkill.o \
	board-fx3-storage.o \
	board-fx3-usb.o \
	board-fx3-input-l9ii.o \
	board-fx3-sensor.o \
	board-fx3-sound.o \
	board-l9ii-misc.o
endif
else
ifndef CONFIG_MACH_LGE_F6_TMUS
obj-$(CONFIG_MACH_MSM8930_FX3) += board-fx3.o \
	board-fx3-camera.o \
	board-fx3-display.o \
	board-fx3-gpiomux.o \
	board-fx3-gpu.o \
	board-fx3-pmic.o \
	board-fx3-regulator.o \
	board-fx3-rfkill.o \
	board-fx3-storage.o \
	board-fx3-usb.o \
	board-fx3-input.o \
	board-fx3-sensor.o \
	board-fx3-sound.o \
	board-fx3-nfc.o
endif
endif
endif
endif
endif
